export const queryKeys = {
  getFarmerAggregatorDashboardCount: 'getFarmerAggregatorDashboardCount',
  getFarmerAggregatorRecentProduce: 'getFarmerAggregatorRecentProduce',
  getExporterDashboardCount: 'getExporterDashboardCount',
  getIndividualFarmer: 'getIndividualFarmer',
  getPentrarHubProduce: 'getPentrarHubProduce',
  getIMyProduce: 'getIMyProduce',
  getAllFarmers: 'getAllFarmers',
  getAllProduce: 'getAllProduce',
  getSingleProduce: 'getSingleProduce',
  getAdminDashboardCount: 'getAdminDashboardCount',
  getAllAdmins: 'getAllAdmins',
  emailCheck: 'emailCheck',
  getAllSubAdmin: 'getAllSubAdmin',
  getAllAggregator: 'getAllAggregator',
  getIndividualAggregator: 'getIndividualAggregator',
  getAllAgencies: 'getAllAgencies',
  getIndividualAgency: 'getIndividualAgency',
  getAllTransferProduces: 'getAllTransferProduces',
  getIndividualExporter: 'getIndividualExporter',
  getAllExporters: 'getAllExporters',
  getAllProduceHandlers: 'getAllProduceHandlers',
  getAllCertificate: 'getAllCertificate',
  getIndividualCertificate: 'getIndividualCertificate',
  getTeamMemberCount: 'getTeamMemberCount',
};
