export const queryKeys = {
  getFarmerAggregatorDashboardCount: 'getFarmerAggregatorDashboardCount',
  getFarmerAggregatorRecentProduce: 'getFarmerAggregatorRecentProduce',
  getIndividualFarmer: 'getIndividualFarmer',
  getPentrarHubProduce: 'getPentrarHubProduce',
  getIMyProduce: 'getIMyProduce',
  getAllFarmers: 'getAllFarmers',
  getAllProduce: 'getAllProduce',
  getSingleProduce: 'getSingleProduce',
  getAdminDashboardCount: 'getAdminDashboardCount',
  getAllAdmins: 'getAllAdmins',
  emailCheck: 'emailCheck',
  getAllSubAdmin: 'getAllSubAdmin',
  getAllAggregator: 'getAllAggregator',
  getIndividualAggregator: 'getIndividualAggregator',
  getAllAgencies: 'getAllAgencies',
};
